# Generated by Django 4.1 on 2022-08-26 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('car_img', models.ImageField(upload_to='car_img')),
                ('specs', models.FileField(upload_to='specs')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_name', models.CharField(max_length=20)),
                ('dealerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dealers', to='myapp.car')),
            ],
        ),
    ]
